name: SynchronizeFiles
on:
  push:
    branches:
      - master
jobs:
  synch:
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1.0.1
        with:
          FILE_PATTERNS: |
            ^.github/workflows/scripts/build_and_test.sh$
            ^.github/workflows/scripts/build_docs.sh$
            ^.github/workflows/scripts/get_dependencies.sh$
            ^.github/workflows/scripts/lint.sh$
            ^.clang-format$
            ^.gitignore$
            ^cmake/get_cpp.cmake$
            ^cmake/nwx_cxx_api_docs.cmake$
            ^cmake/nwx_python_mods.cmake$
            ^cmake/FindCppyy.cmake$
            ^docs/requirements.txt$
            ^LICENSE$
          TARGET_REPOS: |
            NWChemEx-Project/Integrals
            NWChemEx-Project/LibChemist
            NWChemEx-Project/MP2
            NWChemEx-Project/SimDE         
            NWChemEx-Project/ChemCache
            NWChemEx-Project/SCF
            NWChemEx-Project/SimDE
            NWChemEx-Project/ParallelZone
            NWChemEx-Project/Mokup
            NWChemEx-Project/Utilities
            NWChemEx-Project/NWChemEx
          GITHUB_TOKEN: ${{ secrets.SYNC_FILES }}
          COMMIT_MESSAGE: "Updating synched files from %SRC_REPO%"
