name: SynchronizeFiles
on: push
jobs:
  synch:
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1.0.1
        with:
          FILE_PATTERNS: |
            ^.clang-format$
            ^.gitignore$
            ^LICENSE$
          TARGET_REPOS: |
            NWChemEx-Project/Utilities
          GITHUB_TOKEN: ${{ secrets.SYNC_FILES }}
          COMMIT_MESSAGE: "Updating synched files from %SRC_REPO%"
