name: Test Documentation
on:
  pull_request:
    branches:
      - master

jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain Source
        uses: actions/checkout@v2
      - name: Get dependencies
        env:
          cmake_version: ${{ matrix.cmake_version }}
        run: .github/workflows/scripts/get_dependencies.sh sphinx
      - name: Build documentation
        run: |
          . venv/bin/activate
          cd docs
          make html
